### ISSUE TITLE
Please update and include the language files into the master branch

### ISSUE THREAD

**Issue by ShortBusKing** [YodasMyDad/mvcforum#100]
Please also merge these language files into the master branch.
[en-US.csv](https://github.com/ShortBusKing/mvcforum/blob/Oracle-concept/MVCForum.Website/Installer/en-US.csv)
[en-GB.csv](https://github.com/ShortBusKing/mvcforum/blob/Oracle-concept/MVCForum.Website/Installer/en-GB.csv)

**Comment by ransems** [comment]
I also wondered about adding labels once the code is deployed?  how to update database with a new field label?  Any one...
