### ISSUE TITLE
cant's connect  SQL Server 

### ISSUE THREAD

**Issue by wendy2017666** [YodasMyDad/mvcforum#117]
[SqlException (0x80131904): 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接)]

**Comment by wezmag** [comment]
Have you checked your connection string?
BTW, please post your error message in English, so @YodasMyDad can understand your question.
Thanks

**Comment by wendy2017666** [comment]
Thanks,I am in China，Haha，I'll be careful next time

**Comment by CodeHeight** [comment]
Named Pipes Provider, error: 40  normally means your application can not connect to your database.  Review your connectionstring.

**Comment by yesan** [comment]
@wendy2017666 Hi boy,Did you solved the problem of SqlConnection ?Could you tell me?I meet the same.
