### ISSUE TITLE
Where the initialization admin password？

### ISSUE THREAD

**Issue by yesan** [YodasMyDad/mvcforum#118]
When I deployed mvcforum,I found the admin username in the MembershipUser table at the database，but the password is encrypted。How can i get the admin password?

**Comment by wezmag** [comment]
If you didn't change the seed method in data migration configuration, the default password for admin is "password".

https://github.com/YodasMyDad/mvcforum/blob/master/MVCForum.Services/Migrations/Configuration.cs#L332

**Comment by yesan** [comment]
@wezmag Thank you
