### ISSUE TITLE
Is it hard to use an external OpenID provider?

### ISSUE THREAD

**Issue by mfidemraizer** [YodasMyDad/mvcforum#124]
Hi! Probably I'll use MvcForum to build some small community but I need to authenticate users againsts an OpenID relying party. 

Is it hard to implement this? Will you guide me on what could be the first steps to get it working?

Thank you in advance.

**Comment by ransems** [comment]
The code is designed to work with OpenIDs from MS, Google and Facebook, why do you think you need to use an OpenID relying party? Seems like a lot of work for no benefit. All of the APIs are free to use for OAuth, and each company support is already built into SkyBrud.Social. No need to reinvent the wheel IMHO. Get a few appIds/secrets and it works as expected.
