### ISSUE TITLE
Poll questions should not be editable after creation 

### ISSUE THREAD

**Issue by dhinesh333** [YodasMyDad/mvcforum#125]
When I create a post with polling, I can't able to reedit it. SQL exception occurred while saving the entities 

Please find the exception message below, 

The DELETE statement conflicted with the REFERENCE constraint "FK_dbo.PollVote_dbo.PollAnswer_PollAnswer_Id". The conflict occurred in database "DevSyncfusionQuestions", table "dbo.PollVote", column 'PollAnswer_Id'.
The statement has been terminated.

Thanks,
Dhinesh V.

**Comment by YodasMyDad** [comment]
We need to make them not editable if a vote has been cast on any answer.
