### ISSUE TITLE
Separate permission to create tags

### ISSUE THREAD

**Issue by PhonicUK** [YodasMyDad/mvcforum#128]
My users are really crappy at using tags properly, stuffing all manner of garbage in there - so I'd love a way to be able to prevent users from creating their own tags, instead only allowing a fixed selection provided by Admins.

**Comment by ransems** [comment]
add a table and wire up the Tags field with a dropdown (multiselect, or DDL and add button, pulling from and filtering from the table you create and populate with Admin created tags. Should be easy enough to do with the source code given. Add an Admin CRUd in the back end for you to edit/create tags.
