### ISSUE TITLE
Issue with WebActivator dependency

### ISSUE THREAD

**Issue by rbmiller12** [YodasMyDad/mvcforum#130]
Getting this error during install - 
install-package : Unable to find dependent package(s) (WebActivator)

I installed it manually using Install-Package WebActivator -RequiredVersion 1.5.3, but TheMVCForum still errors out.  Also tried 1.5.2, same error.

**Comment by ransems** [comment]
I am using 1.5.2 and do not see 1.5.3 available, can you remove and reinstall 1.5.2. Alls well with my copy. recent pull.
