### ISSUE TITLE
Error when try to build on visual studio

### ISSUE THREAD

**Issue by saptarshisengupta** [YodasMyDad/mvcforum#132]
i have downloaded the source code and when i was trying yo build on visual studio i got many errors,also restore nuget packages but still it is not fixed please help me.

**Comment by blandyuk** [comment]
What version of VS you using? I'm using VS2017 Pro and it compiled OK with no issues. What version of MVCForum? I'm using v1.9.2.

**Comment by YodasMyDad** [comment]
You have to use VS2017
