### ISSUE TITLE
Users to choose their own theme

### ISSUE THREAD

**Issue by blandyuk** [YodasMyDad/mvcforum#135]
My forums which were written by me gave the users the ability to choose their own theme. This was used a lot by my users and will be requested for sure.

You need to allow users to be able to select their own theme. Have the system default but, once users have registered, when they "Edit" their profile, they can select a theme.

I also have problems with your themes as they are difficult to edit. You should have used standard bootstrap themes from https://bootswatch.com/ as this would have made theme changing **a lot** easier. You could then have had another CSS controlling any custom items which would have been easy to change.

**Comment by blandyuk** [comment]
OK, I've had fun splitting out the themes but, I've managed to create a dark theme based on the bootswatch website and the "Slate" theme :)

If anyone wants it let me now. Also, I can do any of their themes now as it should be easier to add them.

**Comment by YodasMyDad** [comment]
This is not something I will be adding.
