### ISSUE TITLE
Can't delete a user due to a relationship constraint.

### ISSUE THREAD

**Issue by PhonicUK** [YodasMyDad/mvcforum#139]
An error occurred while saving entities that do not expose foreign key properties for their relationships. The EntityEntries property will return null because a single entity cannot be identified as the source of the exception. Handling of exceptions while saving can be made easier by exposing foreign key properties in your entity types. See the InnerException for details. 

INNER EXCEPTION: A relationship from the 'BadgeTypeTimeLastChecked_User' AssociationSet is in the 'Deleted' state. Given multiplicity constraints, a corresponding 'BadgeTypeTimeLastChecked_User_Source' must also in the 'Deleted' state.

**Comment by drlivsi** [comment]
Hi PhonicUK,
Could you please share information 'how to reproduce this issue' ?
Thanks

**Comment by PhonicUK** [comment]
* Create a new user, validate and login
* New user visits their own profile page (/profile/USER)
* Admin user finds the user via Manage Users and hits delete
* Exception shows in log

**Comment by blandyuk** [comment]
On the [BadgeTypeTimeLastChecked] table, there is a relationship constraint to the [MembershipUser] table via the [Id] field. The constraint do not cascade deletes and remove the rows from the [BadgeTypeTimeLastChecked] table, hence you issue.

Change the "Delete Rule" on the relationship to "Cascade" and it should resolve your issue.
