### ISSUE TITLE
Fixed several badge check conditions

### ISSUE THREAD

**Issue by siaonong** [YodasMyDad/mvcforum#141]
I just realised that 2 badges won't be applied correctly because their conditions are wrong. Don't know how to push my fixes on Github so I put them here below.

**Badge.FavouriteFirstPostBadge.cs**
public class FavouriteFirstPostBadge : IFavouriteBadge
{
　public bool Rule (MembershipUser user) {
　　return user.Favourites.Count >= 1; _// Should add = symbol_
　}
}

**Badge.UserVoteUpBadge.cs**
public class UserVoteUpBadge : IVoteUpBadge
{
　public bool Rule (MembershipUser user) {
　　return user.VotesGiven != null && user.VotesGiven.Count >= 1;   _//Should be VotesGiven instead of Votes_
　}
}

**Comment by siaonong** [comment]
**Users who mark his post as the solution to his own topic will be awarded "Your Question Solved" and "Post Selected As Answer" twice.**

It's because the **MarkAsSolution() of BadgeController will call badgeService.ProcessBadge() twice**, once for the author of the topic (post.Topic.User), once for the author of the solution post (post.User). So the user will be awarded 2 badges as the author of the topic once and be awarded those 2 badges again as the author of the solution post.

I fixed this problem by adding an if statement in **MarkAsSolution() of BadgeController** as below:

**if (post.User != post.Topic.User) {
　databaseUpdateNeeded = _badgeService.ProcessBadge(BadgeType.MarkAsSolution, post.User) | _badgeService.ProcessBadge(BadgeType.MarkAsSolution, post.Topic.User);
} else {
　databaseUpdateNeeded = _badgeService.ProcessBadge(BadgeType.MarkAsSolution, post.User);
}**

**Comment by YodasMyDad** [comment]
Thanks. Will merge manually due to large refactor in v2
