### ISSUE TITLE
Problems integrating Microsoft login.

### ISSUE THREAD

**Issue by jrnsr8500** [YodasMyDad/mvcforum#143]
I'm having issues integrating with Microsoft login.  I get the error below.  The super funny thing is that I tried registering on here using Microsoft and received the same user-facing error!

Validation failed for one or more entities. See 'EntityValidationErrors' property for more details. The validation errors are: The field MicrosoftAccessToken must be a string or array type with a maximum length of '450'. 

As a side note, to keep from getting the generic (useless) EntityValidationErrors, you can catch the DbEntityValidationException exception and loop through the exception.EntitiyValidationErrors.ValidationErrors to include the actual error messages from the Exception.  I found this very useful when troubleshooting issues with EF.

**Comment by YodasMyDad** [comment]
Thanks. I'll increase the length of that field
