### ISSUE TITLE
Support for Asp.Net Core

### ISSUE THREAD

**Issue by layinka** [YodasMyDad/mvcforum#144]
Thanks for the great work

Any plans for migrating to Asp.Net core?

**Comment by mchenx** [comment]
any plans for upgrading to asp.net core + angular 5 ?

**Comment by YodasMyDad** [comment]
It's planned, but v2.0 needs to be released first which has some breaking changes. Hopefully will be released end of Jan. Then I'll be looking to move to .NET core properly and update UI to probably use vue.js

**Comment by endink** [comment]
+1 hope

**Comment by hansvonn** [comment]
Do you have a road map?

**Comment by kanpinar** [comment]
+1

**Comment by DylanFPS** [comment]
> It's planned, but v2.0 needs to be released first which has some breaking changes. Hopefully will be released end of Jan. Then I'll be looking to move to .NET core properly and update UI to probably use vue.js
ASP.NET Core 2 has been released for a while, any updates on this?
