### ISSUE TITLE
Exception on creating new forum

### ISSUE THREAD

**Issue by HClausing** [YodasMyDad/mvcforum#147]
Good afternoon.

I'm trying to start a new fórum, using 1.9.2 version from Nuget Package (starting with na empty Web Application, as described on tutorial), and on debug, I'm getting this exception:

ArgumentNullException: Value cannot be null. 
Parameter name: value
    System.Runtime.Caching.MemoryCacheEntry..ctor(String key, Object value, DateTimeOffset absExp, TimeSpan slidingExp, CacheItemPriority priority, Collection`1 dependencies, CacheEntryRemovedCallback removedCallback, MemoryCache cache) +60190
    System.Runtime.Caching.MemoryCache.AddOrGetExistingInternal(String key, Object value, CacheItemPolicy policy) +483
    System.Runtime.Caching.MemoryCache.AddOrGetExisting(CacheItem item, CacheItemPolicy policy) +50
    System.Runtime.Caching.MemoryCache.Add(CacheItem item, CacheItemPolicy policy) +15
    MVCForum.Services.CacheService.Set(String key, Object data, CacheTimes minutesToCache) +247
    MVCForum.Services.SettingsService.GetSettings(Boolean useCache) +101
    MVCForum.Website.MvcApplication.Application_Start() +502

It happens at startup. I can't see the home page.

**Comment by YodasMyDad** [comment]
Do no use the nuget package. It's been dropped for the time being.
