### ISSUE TITLE
Register is broken due to email confirmation

### ISSUE THREAD

**Issue by arnonax** [YodasMyDad/mvcforum#160]
Whenever I try to register and login to https://support.mvcforum.com I get an error:

> Index was outside the bounds of the array.
> `Line 6:          <div class="alert alert-block alert-info"> Line 7:              <a href="#" data-dismiss="alert" class="close">&times;</a> Line 8:              @Html.LanguageString("Members.MemberEmailAuthorisationNeededMessage") <a class="btn" href="@Url.Action("ResendEmailConfirmation", "Members", new {username = splitCookie[1]})">@Html.LanguageString("Members.MemberEmailAuthorisationResend")</a> Line 9:          </div> Line 10:     }
> --`
> Source File: c:\inetpub\wwwroot\MVCForum\htdocs\Views\Shared\_EmailConfirmationNotice.cshtml    Line: 8 
> 

I tried it from different computers and with different usernames and passwords.
Note that when I register (using a new username) I see it in the Activities, but I still can't login.

**Comment by YodasMyDad** [comment]
Thanks. I'm looking into this now.

**Comment by YodasMyDad** [comment]
Add Extended data to entities and store guid in that for email confirmation

**Comment by arnonax** [comment]
Hi Lee,

Unfortunately the problem isn’t solved. I just tried to login and got the same exception:
[cid:image001.png@01D38472.B1D598A0]

**Comment by arnonax** [comment]
The image didn't seem to make it when sending it from email. Anyway, it's the same exception. However, I want to emphasize that the problem is related to the https://support.mvcforum.com website, and not directly to the code at GitHub. However because I can't login to the support page, I couldn't report the issue over there... That's why I reported it here as a bug.

**Comment by YodasMyDad** [comment]
Sorry mis-understanding. It's resolved in the v2 master branch which I'll push up to the main site soon.
