### ISSUE TITLE
Topic slug generation

### ISSUE THREAD

**Issue by aram-aramyan** [YodasMyDad/mvcforum#192]
I've checked this file /MVCForum.Core/Services/ServiceHelpers.cs and it's obvious that there is a problem with slug generation for topic.
If there is a topic with slug="topic-name-1" and one with slug="topic-name-2" and you try to create a new one with slug="topic-name" then the user wil not see any errors - the topic is just not saved.

The problem can be solved using a **while** instead of **if**. But I don't think it's the best solution.

I think the best way is to have the topicId in the slug. The generated slug should look something like 'topic-name--XXX' where 'XXX' is the topicId. This solution will also let us find the topic by Id and not the slug and is better for SEO (if you change the topic title - the old links to that topic will work - we could 301 redirect the user to the new topic url).

**Comment by YodasMyDad** [comment]
Thanks. I'll fix this in v2
