### ISSUE TITLE
Cannot delete topics with poll in version 1.9.3

### ISSUE THREAD

**Issue by ic-cedwards** [YodasMyDad/mvcforum#201]
User creates a topic and adds a poll. This poll can be edited at this point.

Someone votes on poll.

 1) When you go into edit the topic, the voted option is greyed out (fair enough, cannot change a voted for option, makes sense) however, the other unvoted-for options remain white and suggest it can be edited. If you try and then click on "edit" (also confusing, should say "save changes" not "edit" as you already are editing) you get "you do not have permission", etc.  Kind of makes it pointless leaving the unvoted-for options editable then really?

2) Most serious - you can't delete anything now!  Try to delete the topic and you get an error: "Sorry, an error occurred".  How do you now delete a topic?  You cannot remove the poll from the topic, so that's out.

The only way around this I found was to go to back end database, delete the poll ID from the topic and THEN you can delete the topic and any posts on it.

**Comment by YodasMyDad** [comment]
This is fixed in v2

**Comment by ic-cedwards** [comment]
I knew you were going to say that!  Is there a trail of code where this is fixed as I have made a lot of modifications to the source on our server now and I don't want to just overwrite it.

**Comment by ic-cedwards** [comment]
Is this in #179 or #125 ?

**Comment by YodasMyDad** [comment]
It's in both. v2.0 is a complete rewrite as it's using pipeline system now.
