### ISSUE TITLE
Still cannot delete topic with poll even in new version 2.0

### ISSUE THREAD

**Issue by ic-cedwards** [YodasMyDad/mvcforum#208]
Following my post about this problem in #201 I went to the trouble of creating a completely new repo, downloaded latest version and upgraded my visual studio to 2017. I then spent 2 days reapplying all my changes to the new version.

Guess what?  Still cannot do this.  I get 'The method or operation is not implemented. ' as soon as I try to delete.

Steps to reproduce:
1. Create topic, add poll (I did this as user with admin privilege)
2. Vote on poll and submit.
3. Log in as different user with admin permissions
4. Press delete button and "ok" on "are you sure" box.
5. Get "The method or operation is not implemented. " error.

What next then?

**Comment by ic-cedwards** [comment]
It's not just topics with polls.  Did the same procedure with a post and couldn't delete it even though it has no poll.

**Comment by ic-cedwards** [comment]
And cannot delete the post even if logged in as the person who posted it. Who has admin rights.

**Comment by ic-cedwards** [comment]
The exception fires on this line (no. 73) in "PostDeletePipe.cs"
`await _membershipUserPointsService.Delete(input.EntityToProcess.User, PointsFor.Post, input.EntityToProcess.Id);`

**Comment by YodasMyDad** [comment]
Ok thanks. I'll try and repo in a mo and get it fixed.

**Comment by ic-cedwards** [comment]
I had "allow points" turned off in admin and thought it might be that, but when I enabled them the error still happens. If I comment out the delete points section then it all works as expected.

**Comment by YodasMyDad** [comment]
Did you get an exception? Could you copy and paste here?

**Comment by ic-cedwards** [comment]
What - other than 'The method or operation is not implemented. '?

**Comment by YodasMyDad** [comment]
Is that what you got?

**Comment by YodasMyDad** [comment]
I pushed up to the master branch over the last few days and fixed that not implemented bug? Which is why I'm asking before I start hunting this down. As I've just tried quickly and it's working fine for me on latest codebase.

**Comment by ic-cedwards** [comment]
OK, will do a fetch and see if that cures it, hang on

**Comment by ic-cedwards** [comment]
What number was the fix you mentioned just then?

**Comment by YodasMyDad** [comment]
Yeah. You definitely need to pull all the latest changes not just that one as other things have been fixed. However, this was the fix

https://github.com/YodasMyDad/mvcforum/commit/e27b68552c7faeadeba53e56e0a3eaeb445c9d05#diff-927e86678ceff6eedfd304b668644c6f

I'm closing this for now.
