### ISSUE TITLE
Been testing banned words.  Application seems to ignore forum.config

### ISSUE THREAD

**Issue by ic-cedwards** [YodasMyDad/mvcforum#210]
I have a debug break point on line 28 of ConfigUtils.cs.  It's trying to return a setting for `WebConfigurationManager.AppSettings[appSettingame]` where appSettingame is currently set to BannedWordReplaceCharactor.

Problem is, as far as the app is concerned at this point it is only looking at the 4 appsettings in web.config:
```
<appSettings>
    <add key="webpages:Version" value="3.0.0.0"/>
    <add key="PreserveLoginUrl" value="true"/>
    <add key="ClientValidationEnabled" value="true"/>
    <add key="UnobtrusiveJavaScriptEnabled" value="true"/>
  </appSettings>

```
That's all it has in memory if you inspect WebConfigurationManager.AppSettings.

**Comment by YodasMyDad** [comment]
Nice find! Thanks for testing everything. I've just fixed that and pushed it up
