### ISSUE TITLE
Payment Issues

### ISSUE THREAD

**Issue by talha020** [YodasMyDad/mvcforum#213]
What is other option available then PayPal to get domain license cause PayPal is not yet available for some countries?

**Comment by YodasMyDad** [comment]
I'll have a look and see if I can find a better option.

**Comment by talha020** [comment]
Yup tell me cause I want to buy a license for my domain.And in Pakistan, Paypal yet not accepted.

**Comment by YodasMyDad** [comment]
What are the popular payment providers over there out of interest?

**Comment by talha020** [comment]
Payoneer.But personally never used it though.

**Comment by talha020** [comment]
Can you tell me one thing who is real Digioz or MVC forum @YodasMyDad?

**Comment by talha020** [comment]
Then please tell me what I do?Can I use MVCForum without license key!

**Comment by YodasMyDad** [comment]
Sorry nothing I can do right now, I'm going to look into it further soon.
