### ISSUE TITLE
Spelling error in page

### ISSUE THREAD

**Issue by ic-cedwards** [YodasMyDad/mvcforum#216]
In the "following" page there is a sub-title of  "Topics **your** are following" which should be "Topics **you** are following".  This can be fixed by an admin by editing the "Following.Topics" key in the language file.

You will probably need to recycle your app pool to see the change made due to caching.

**Comment by YodasMyDad** [comment]
Feel free to do a PR for this ;) ... You can change the language CSV files.

**Comment by ic-cedwards** [comment]
Oh. in the installation folder - does it use those to seed the database then?

**Comment by YodasMyDad** [comment]
Yes, it uses the en-GB as the default. The others are there in case you need them. They were added by PR's from different people.

**Comment by ic-cedwards** [comment]
Closing issue as I've done pull request to fix
