### ISSUE TITLE
Trying to resend email and getting this error

### ISSUE THREAD

**Issue by BaiMangal** [YodasMyDad/mvcforum#219]
Sceenshot of the error here:
http://prntscr.com/ijc407

Also the link in the email for new user confirmation when clicked says unable to login

**Comment by YodasMyDad** [comment]
What version are you using please?

**Comment by BaiMangal** [comment]
2.0 beta2

 

Also when I login with FB or G and go an change the Name it changes the username and it gives an error.

**Comment by YodasMyDad** [comment]
Thanks for letting me know. Can you raise another issue fir the issue with the FB and G name change issue please.

**Comment by YodasMyDad** [comment]
Sorry, when you say trying to resend email? Can you confirm what you mean?

**Comment by BaiMangal** [comment]
Created a new user and had the settings that use needs to validate their email. 
The user didnt receive a confirmation email as I had forgotten to add smtp settings. Added them and tried the user to click the Resend Email button and got the error above.

**Comment by YodasMyDad** [comment]
Ok thanks. This will be fixed in next set of changes pushed up
