### ISSUE TITLE
2.0 beta2 uploading image error

### ISSUE THREAD

**Issue by BaiMangal** [YodasMyDad/mvcforum#221]
I dont get an error on the screen just those
![image](https://user-images.githubusercontent.com/6637745/36855258-e7691596-1d6a-11e8-8f54-01a066b9e4a4.png)
 and then the box becomes like this

![image](https://user-images.githubusercontent.com/6637745/36855288-f9fbb7f4-1d6a-11e8-87dc-e488f35ebb16.png)

**Comment by BaiMangal** [comment]
Actually I just realised that this is probably an issue as I host with azure web apps and there is no disk drive available really.
Not sure what to do though so I could have images.
Any ideas what to use if there is no disk?

**Comment by BaiMangal** [comment]
I can see the images are uploaded to the web server
![image](https://user-images.githubusercontent.com/6637745/36871404-143bf7c6-1d9a-11e8-8392-089e186d2975.png)

**Comment by YodasMyDad** [comment]
Have you pulled the latest changes? As I cannot replicate this.

**Comment by BaiMangal** [comment]
I couldn't build from the source code so I am using the released build from here https://github.com/YodasMyDad/mvcforum/releases
this one MVCForum-v2.0-Beta2.zip

Could you do a new build for me and I will test please?
