### ISSUE TITLE
Azure storage integration

### ISSUE THREAD

**Issue by carlfm01** [YodasMyDad/mvcforum#223]
For file intensive forums can be a great option.

**Comment by YodasMyDad** [comment]
This is something you can do yourself via a plugin, it comes with a DiskStorageProvider OOTB

https://github.com/YodasMyDad/mvcforum/blob/master/MvcForum.Plugins/Providers/DiskStorageProvider.cs

 Just create a class called BlobStorageProvider and implement IStorageProvider and add the logic for the methods required.

Then just swap out the provider in the config to point to yours and that's it.

https://github.com/YodasMyDad/mvcforum/blob/master/MVCForum.Website/App_Data/forum.config#L129
