### ISSUE TITLE
Pretty major issue - cannot edit a reply on a topic when not original poster

### ISSUE THREAD

**Issue by ic-cedwards** [YodasMyDad/mvcforum#225]
Weird this. Make a new topic post. Add a reply from a different basic account (with no permission to edit anyone else's posts).  Try to edit that last post and you get a permissions error because for some reason the pipeline attempts to edit all posts in the topic, including the original topic. 

Why does it do this? this is a really common thing for any forum user to want to do (edit their own post).

**Comment by YodasMyDad** [comment]
Can you pull latest changes and see if it still does it.

**Comment by ic-cedwards** [comment]
Yes, it's fine now. Sorry, I was hammering on the "fetch" button in my dev environment and it kept telling me there were no incoming changes.  Turns out there were incoming changes and it just wasn't telling me about them for some reasons. After a rebuild it started working, thanks.  Can close now.

**Comment by vikekh** [comment]
@ic-cedwards You've got to merge after fetching. Pull is a fetch, followed by a merge. :)
