### ISSUE TITLE
CacheTimes is off by a factor of 60?

### ISSUE THREAD

**Issue by bsimser** [YodasMyDad/mvcforum#227]
Not sure if this an issue or not but it looks like it.

In CacheTimes.cs this enum lists the numbers to use:

`public enum CacheTimes`
`    {`
`        OneMinute = 1,`
`        OneHour = 60,`
`        TwoHours = 120,`
`        SixHours = 360,`
`        TwelveHours = 720,`
`        OneDay = 1440`
`    }`

So it's called in placed like the Home Controller like this:

`[OutputCache(Duration = (int)CacheTimes.TwoHours)]`

Problem is that the documentation for the OutputCache Duration value is the cache duration in seconds, not minutes.

https://msdn.microsoft.com/en-us/library/system.web.mvc.outputcacheattribute.duration(v=vs.118).aspx#P:System.Web.Mvc.OutputCacheAttribute.Duration

So CacheTimes.OneMinute should be 60, not 1 and CacheTimes.TwoHours should be 7200 not 120.

Or am I missing something in the codebase?

**Comment by YodasMyDad** [comment]
Definitely a bug thanks

**Comment by bsimser** [comment]
Thanks. Would have submitted a PR but wanted to make sure I wasn't misinterpreting anything in the code first.
