### ISSUE TITLE
New Discussion not working

### ISSUE THREAD

**Issue by dcraggs** [YodasMyDad/mvcforum#256]
Got the latest version and ran it, but New Discussion is not working. Just getting "Sorry an error occurred".

This worked on an earlier version. Tried it on a blank database as well as an existing migrated database. Tried to look at the code, but I'm not familiar with PipeLines.

**Comment by dcraggs** [comment]
Ignore this - Now working.

**Comment by codeincolor** [comment]
@dcraggs  What did you do that fixed it?  I am having the same issue.  I would prefer not to have to learn pipelines if I can avoid it.  Thanks!

**Comment by codeincolor** [comment]
Issue Resolved. The pipelines look for assemblies that are loaded on app start. The default directory for these assemblies is app_data. But.. Initially there is nothing in there. You must first compile the project MvcForums.Plugins before running the web project. This will create the assembly needed to properly save to the db. Note: I created the Plugins folder manually.
