### ISSUE TITLE
View Overriding

### ISSUE THREAD

**Issue by dmeehan** [YodasMyDad/mvcforum#65]
The docs for Theme View Overriding say this:

> "The theme engine also has view overriding. A good example of this is the default metro theme that comes with the forum, if you open up the Metro theme folder in the views sub folder you will see it has its own '_Layout.cshtml' this overrides the root _Layout.cshtml in the root views folder.
> 
> You can do this for any view you want to change, so if you wanted to change the default view for the Private Messages. Just copy and paste the view into your Theme folder, making sure its mimicking the structure of where the original is placed i.e."

Do these instructions still apply? I can't seem to find any Metro theme folder within the Views folder. Using _Layout.cshtml as an example, does the pattern for overriding look like:

 Views --> Metro --> Views --> Shared --> _Layout.cshtml

Or is the pattern:

 Themes --> Metro --> Views --> Shared --> _Layout.cshtml

 Or is it some other pattern I am missing?

Thanks.

**Comment by YodasMyDad** [comment]
Always from the theme folder, as it states in the description.

> Just copy and paste the view into your **Theme** folder, making sure its mimicking the structure of where the original is placed
