### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by craigs100** [YodasMyDad/mvcforum#66]
Just installed V1.8. Logged in as Admin ok. Logged out and attempted to register as a new member. On clicking the "Register" button two boxes appear. A green one saying "You are now registered" and a red one saying "An error occurred".  Logging in as admin and looking at the Membership > Manage Users section there is only the Admin account showing.

Logs show:-
`Validation failed for one or more entities. See 'EntityValidationErrors' property for more details. The validation errors are: The field Body must be a string or array type with a maximum length of '4000'.`

Cheers,
Craig

**Comment by YodasMyDad** [comment]
Good catch. It's a SQLCE issue and purely down to the email body field being too long to store in SQLCE. I've just pushed up a stripped down email (Not ideal but it has to work on both SQLCE and MSSQL).
