### ISSUE TITLE
use MySql Private Messages Error

### ISSUE THREAD

**Issue by jibie** [YodasMyDad/mvcforum#70]
Class PrivateMessageService, Fun GetUsersPrivateMessages
“System.Data.Entity.Core.EntityCommandExecutionException”
"Unknown column 'Distinct1.C1' in 'where clause'"
Suggestion: give priority to with Mysql development

**Comment by YodasMyDad** [comment]
Sorry MySql is not supported.

**Comment by huchao007** [comment]
Sqlserver is good来自我的华为手机-------- 原始邮件 --------主题：Re: [YodasMyDad/mvcforum] use MySql Private Messages Error (#70)发件人：Lee 收件人：YodasMyDad/mvcforum 抄送：Sorry MySql is not supported.
