### ISSUE TITLE
Compilation problem with interpolation "$"

### ISSUE THREAD

**Issue by aliziani** [YodasMyDad/mvcforum#74]
Hello,

Apparently i can't create a pull request for the wiki project.
Could you add the text below at the end of the "Installing.md" file plz ?

**Remark**

You need to use Visual Studio 2015 because the project use functionnalities from
C# 6 (ex: interpolation) which are not managed by previous versions of Visual Studio.

Sources:

1. http://stackoverflow.com/questions/31514767/string-interpolation-doesnt-work-with-net-framework-4-6
2. http://stackoverflow.com/questions/31721498/tfs-wont-compile-string-interpolation-syntax

**Comment by YodasMyDad** [comment]
Please use VS2015 to update the source code
