### ISSUE TITLE
Build error?

### ISSUE THREAD

**Issue by okings** [YodasMyDad/mvcforum#77]
![image](https://cloud.githubusercontent.com/assets/11713429/16942793/9e4ac380-4dca-11e6-94cf-297a59ea2ab7.png)

I download source code from github(zip), build and show error above , pls help me ?

**Comment by okings** [comment]
I debugger Code, found:
In method "GetSettings", cachedSettings return null value.

------------------------------------------------------

        public Settings GetSettings(bool useCache = true)
        {
            if (useCache)
            {
                var cachedSettings = _cacheService.Get<Settings>(AppConstants.SettingsCacheName);
                if (cachedSettings == null)
                {
                    cachedSettings = GetSettingsLocal(false);
                    _cacheService.Set(AppConstants.SettingsCacheName, cachedSettings, CacheTimes.OneDay);
                }
                return cachedSettings;
            }
            return GetSettingsLocal(true);
        }

**Comment by YodasMyDad** [comment]
Are you using VS2015? And did you update the connection string to point to a blank database?

**Comment by okings** [comment]
OK, i get it. I use VS2013
