### ISSUE TITLE
Posted In error！！

### ISSUE THREAD

**Issue by yangguang111lll** [YodasMyDad/mvcforum#82]
![qq 20160811131509](https://cloud.githubusercontent.com/assets/20963499/17579612/f51149a8-5fc9-11e6-8f17-3a65fb5810ca.jpg)

**Comment by teduinternational** [comment]
I also got this error.

**Comment by YetaWF** [comment]
It would be so much more helpful if you included what specifically you were doing at the time the error occurred. I used 1.8 and was not seeing this error. I now upgraded to 1.9 and I'm still not seeing this error.

**Comment by YodasMyDad** [comment]
Fixed in v1.9.1 coming out in a week.

**Comment by yangguang111lll** [comment]
thanks!
