### ISSUE TITLE
Calculation of post count for a category

### ISSUE THREAD

**Issue by CodeZombieCH** [YodasMyDad/mvcforum#91]
Hi

I noticed that the number of posts in a category is not the what I expect it to be.

Example category:

```
Topic #1
    - Question
    - Answer #1

Topic #2
    - Question
    - Answer #1
    - Answer #2
    - Answer #3
    - Answer #4
    - Answer #5
```

For this example category the current implementation calculates 7 posts. I expect it to be:
- 8, in the case you also count the question
- 6, in the case you do not count the question (TopicStarter flag not set)

The current implementation substracts 1 from the calulated total.

```
var postCount = (actualPostCount < 1 ? actualPostCount : actualPostCount - 1);`
```

_(See: https://github.com/YodasMyDad/mvcforum/blob/master/MVCForum.Website/Views/Category/ListMainCategories.cshtml#L20)_

Unfortunatelly I do not understand why.

Can you please help me on whats the logic behind this?

**Comment by YodasMyDad** [comment]
That's a bug in that case

**Comment by wasnlosdu** [comment]
#121 will fix this issue. Please accept pull req

**Comment by linkaross** [comment]
if this is your math question the question is x2 + 1 = 0 = 2 + 3*i*.
