### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ghost** [YodasMyDad/mvcforum#95]
Hi @YodasMyDad , I'm busy building a forum for my alliance which is bind to a game. 

I was wondering can I tear this forum a apart and use the pieces I need?

If I may would you like me to provide you any credits?

So basically I would like to use some of your code.

Please if you can write to me at di48l069@gmail.com

**Comment by YodasMyDad** [comment]
Sure. If you are using the software in whatever way, then you need to leave the powered by link unless you purchase a copyright removal http://www.mvcforum.com/license/

**Comment by di48l069** [comment]
@YodasMyDad Thank you will defiantly purchase the copyright removal but if I may ask can I build the site first see how it goes then purchase the removal when I get paid on the 25th of this month? Is that alright with you?

If its alright may I ask once I purchased it I may do anything with it and claim it as mine correct?

**Comment by YodasMyDad** [comment]
Of course, whatever works for you. The domain is then registered in our database of licensed applications.

**Comment by di48l069** [comment]
@YodasMyDad Cool so I just give you the domain name and then i'm sorted correct?

**Comment by YodasMyDad** [comment]
http://www.mvcforum.com/copyright-removal-key/

**Comment by di48l069** [comment]
Haha cool thank you I will purchase it on 25th this month have a great day and thank you for help
