### ISSUE TITLE
Deploy error: Microsoft.AspNet.WebApi.WebHost.5.2.3 not found

### ISSUE THREAD

**Issue by LeiYangGH** [YodasMyDad/mvcforum#98]
After download, then restore packages, then rebuild, succeeded.
But, when select `Index.cshtml` and right click browse in chrome, the webpage reports that error. and hosting in IIS has the same error, if do not manually copy dlls from nuget packages folder to bin folder.
After checking for long time, I found that project `MVCForum.IOC` reference this dll from **Visual Studio install location**(whose version is 4.x.x.x), instead of **nuget packages folder**(whose version is 5.x.x.x and I think is the correct one). After changing that, then rebuild then browse, the error disappeared. 
Is this an issue? or did I wrongly debug? I'm not very familiar with how VS distinguish and choose versions.

**Comment by ransems** [comment]
Sometimes if you update a NuGet package and an specific line in the Web.Config has a version number attributed, it might not increment the number properly. So searchm change and save the web.config file and all should be well.  
I had the same thing happen with the 
<dependentAssembly>
        <assemblyIdentity name="Quartz" publicKeyToken="f6b8c98a402cc8a4" culture="neutral" />

        <bindingRedirect oldVersion="0.0.0.0-2.6.0.0" newVersion="2.6.0.0" />
</dependentAssembly> 

I changed to 6.0 and all worked.

**Comment by LeiYangGH** [comment]
thanks!

**Comment by YodasMyDad** [comment]
I'll lo
